name: Android CI

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check LTW file
        run: |
          if [ ! -f app_pojavlauncher/libs/ltw.aar ]; then
            echo "LTW file missing!"
            exit 1
          fi

      - name: Create out directory
        run: mkdir -p out

      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew :app_pojavlauncher:assembleFullDebug
          mv app_pojavlauncher/build/outputs/apk/full/debug/app_pojavlauncher-full-debug.apk out/app-debug-full.apk

      - name: Build Debug APK (No runtime)
        run: |
          ./gradlew :app_pojavlauncher:assembleNoruntimeDebug
          mv app_pojavlauncher/build/outputs/apk/noruntime/debug/app_pojavlauncher-noruntime-debug.apk out/app-debug-noruntime.apk

      - name: Generate MD5 checksums
        run: |
          md5sum out/app-debug-full.apk > out/app-debug-full.md5
          md5sum out/app-debug-noruntime.apk > out/app-debug-noruntime.md5

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: out/app-debug-full.apk

      - name: Upload Debug APK (No runtime)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.apk

      - name: Upload MD5 Checksums
        uses: actions/upload-artifact@v4
        with:
          name: md5-checksums
          path: |
            out/app-debug-full.md5
            out/app-debug-noruntime.md5
